---
- name: Set OS Specific variables
  import_tasks: include-vars.yml

- name: Install Dependencies
  import_tasks: dependencies.yml
  become: true

- name: Install and configure pgbouncer
  import_tasks: pgbouncer.yml
  become: true
