---
# This will need replaced with deb822_repository eventually,
# however module Requires ansible 2.15, ansible pacakage version for Centos7 is 2.9
- name: Add PgBouncer apt repository | apt
  block:
  - name: Add PgBouncer apt-key | apt
    get_url:
      url: "{{ pgbouncer_apt_key_url }}"
      dest: "/etc/apt/trusted.gpg.d/{{ pgbouncer_apt_key_id }}.asc"
      mode: '0644'
      force: true
  - name: Add PgBouncer apt repository | apt
    apt_repository:
      repo: "{{ pgbouncer_apt_repository }}"
      state: present
  when: ansible_os_family == "Debian"


- name: Install PgBouncer
  package:
    name: pgbouncer
    state: present
  register: _pgbouncer_install

- name: Create pgbouncer directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0755
  with_items:
    - "{{ pgbouncer_log_dir }}"
    - "{{ pgbouncer_pid_dir }}"

- name: Create systemd tmpfiles configuration
  template:
    src: tmpfiles.d_pgbouncer.conf.j2
    dest: /usr/lib/tmpfiles.d/pgbouncer.conf
    mode: 0644
  when: ansible_os_family == "Debian"

- name: Divert pgbouncer main configuration file {{ pgbouncer_conf_file }}
  command: dpkg-divert --quiet --local --divert {{ pgbouncer_conf_dir }}.dpkg-divert --rename {{ pgbouncer_conf_file }}
  args:
    creates: "{{ pgbouncer_conf_file }}.dpkg-divert"
  when:
    - _pgbouncer_install.changed
    - ansible_os_family == "Debian"

- name: Create pgbouncer configuration file
  template:
    src: pgbouncer.ini.j2
    dest: "{{ pgbouncer_conf_file }}"
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0600
  notify:
    - reload pgbouncer

- name: Divert pgbouncer hba file {{ pgbouncer_auth_hba_file }}
  command: dpkg-divert --quiet --local --divert {{ pgbouncer_auth_hba_file }}.dpkg-divert --rename {{ pgbouncer_auth_hba_file }}
  args:
    creates: "{{ pgbouncer_auth_hba_file }}.dpkg-divert"
  when:
    - _pgbouncer_install.changed
    - ansible_os_family == "Debian"

- name: pgbouncer hba file {{ pgbouncer_auth_hba_file }}
  template:
    src: pgbouncer_hba.conf.j2
    dest: "{{ pgbouncer_auth_hba_file }}"
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0640
  notify:
    - reload pgbouncer

- name: Divert pgbouncer user list file {{ pgbouncer_conf_dir }}/userlist.txt
  command: dpkg-divert --quiet --local --divert {{ pgbouncer_conf_dir }}/userlist.txt.dpkg-divert --rename {{ pgbouncer_conf_dir }}/userlist.txt
  args:
    creates: "{{ pgbouncer_conf_dir }}/userlist.txt.dpkg-divert"
  when: ansible_os_family == "Debian"

- name: Add users to userlist.txt
  copy:
    dest: "{{ pgbouncer_auth_file }}"
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: 0600
    content: |
      "stats" "passwordless"
      {% for user in pgbouncer_users %}
      "{{ user.name }}" "md5{{ (user.pass + user.name) | hash('md5') }}"
      {% endfor %}
  notify:
    - reload pgbouncer

- name: Ensure pgbouncer service is enabled
  service:
    name: pgbouncer
    enabled: true

- name: Ensure pgbouncer is running
  service:
    name: pgbouncer
    state: started

- name: Configure logrotate | pgbouncer
  template:
    src: "etc_logrotate.d_pgbouncer.j2"
    dest: "/etc/logrotate.d/pgbouncer"
