---
- name: Restart pgbouncer
  service:
    name: pgbouncer
    state: restarted
  become: true

# Note: we are using "service restart" because "service reload" hangs on Centos 7
# for unknown reasons. Something is wrong with SystemD service config file.
- name: Reload pgbouncer
  service:
    name: pgbouncer
    state: restarted
  become: true
