---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

    # RHEL7 provides `python3` in `rhel-7-server-rpms repository
    # RHEL8/9 provide `c-ares` package in `rhel-X-for-x86_64-baseos-rpms` repository
    # UBI repos are missing this, install CentOS baseos repo and install package
    - name: Install dependencies from CentOS Repositories | RHEL 7+
      when: ansible_distribution == "RedHat"
      block:

      - set_fact:
          _tmp_repos:
            - name: base
              url: http://mirror.centos.org/centos/7/os/x86_64/
              gpg: http://mirror.centos.org/centos/7/os/x86_64/RPM-GPG-KEY-CentOS-7
          _tmp_packages:
            - name: python3
              repo: base
        when: ansible_distribution_major_version == "7"

      - set_fact:
          _tmp_repos:
            - name: base
              url: http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/
              gpg: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-Official
          _tmp_packages:
            - name: c-ares
              repo: base
        when: ansible_distribution_major_version == "8"

      - set_fact:
          _tmp_repos:
            - name: base
              url: https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/
              gpg: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-Official
          _tmp_packages:
            - name: c-ares
              repo: base
        when: ansible_distribution_major_version == "9"

      - name: Add Temporary Repositories | RHEL
        yum_repository:
            name: "{{ item.name }}"
            description: "Centos {{ ansible_distribution_major_version }} - {{ item.name }}"
            baseurl: "{{ item.url }}"
            enabled: false
            gpgkey: "{{ item.gpg }}"
        with_items: "{{ _tmp_repos }}"
        loop_control:
          label: "{{ item.name }}"

      - name: Install missing packages | RHEL
        yum:
          name: "{{ item.name }}"
          state: present
          enablerepo: "{{ item.repo }}"
        with_items: "{{ _tmp_packages }}"
        loop_control:
          label: "{{ item.name }}"






    - name: Install prerequisites
      block:
        - name: Update apt cache
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false
          when: ansible_os_family == "Debian"

  roles:
    - role: ansible-role-pgbouncer
      tags:
        - pgbouncer
